name: Build and Package with PyInstaller

on:
  push:
    tags:
      - '*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller main.spec

      - name: Archive the build
        uses: actions/upload-artifact@v3
        with:
          name: xuejimao-publish-windows
          path: dist/scenedetect.exe

  release:
    runs-on: ubuntu-latest
    needs: build-windows

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: scenedetect-windows
          path: ./dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
